version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vc-issuer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c8kvl7tw89zp"
s3_prefix = "vc-issuer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
