AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda

  Lambda function to issue Verifiable Credentials

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  VCIssuerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: vc-issuer/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        Issue:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /issue
            Method: get
      Environment:
        Variables:
          SEED: YourThirtyTwoBytesHexStringSeed

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VCIssuerApi:
    Description: "API Gateway endpoint URL for Prod stage for Issue function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  VCIssuerFunction:
    Description: "Issue Lambda Function ARN"
    Value: !GetAtt VCIssuerFunction.Arn
  VCIssuerFunctionIamRole:
    Description: "Implicit IAM Role created for Issue function"
    Value: !GetAtt VCIssuerFunctionRole.Arn
